version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run:
            name: Install Jfrog CLI
            command: |
                curl -fL https://getcli.jfrog.io | sh 
      - run:
            name: Install and give permissions
            command: |
                curl -fL https://install-cli.jfrog.io | sh 
      - run:
            name: give per
            command: |
                chmod a+x jfrog && sudo mv jfrog /usr/local/bin  
      - run:
            name: Configure  Jfrog CLI
            command: |
              jfrog config add artifactory-server --url="https://akarshagarwal.jfrog.io" --user="akarshagarwal99@gmail.com" --password="Asdf@1234" --interactive=false
      - run:
            name: Docker Build
            command: |
              sudo systemctl status docker
              sudo docker login -u akarshagarwal99@gmail.com -p Asdf@1234 akarshagarwal.jfrog.io
      - run:
            name: Docker Push to Jfrog  Registry
            command: |
              sudo docker build . -t akarshagarwal.jfrog.io/default-docker-local/akarsh:1.0-${CIRCLE_BUILD_NUM}
              sudo jf docker scan akarshagarwal.jfrog.io/default-docker-local/akarsh:1.0-${CIRCLE_BUILD_NUM} --watches admin
              sudo docker push akarshagarwal.jfrog.io/default-docker-local/akarsh:1.0-${CIRCLE_BUILD_NUM}
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py 

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build